on:
  push:
    branches:
      - '*'  # Runs on any push to any branch
  pull_request:
    branches:
      - '*'  # Runs on any pull request targeting any branch
name: Lint commits
jobs:
  lint-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Fixup git permissions
        # https://github.com/actions/checkout/issues/766
        shell: bash
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - uses: actions/setup-node@v4.1.0
      - run: npm install conventional-changelog
      - run: npm install @commitlint/cli
      - run: npx commitlint --from HEAD~${{ github.event.pull_request.commits }} --to HEAD
